Feature/3 streamer list
Team-Sac/site pull request #19
Opened 2023-04-03 18:45 UTC by YoanRouleau

Getting started with stores and twitch streamers

2023-04-03 21:20 UTC, YoanRouleau commented
![image](https://user-images.githubusercontent.com/46955026/229630074-5305c3a6-4be2-4528-a9a8-34d1b1114ed9.jpeg)

2023-04-13 23:49 UTC, geoffreyparrier requested changes

2023-04-13 23:49 UTC, geoffreyparrier commented on server/api/getTwitchStreamers.post.ts
> +  console.log(data);
Remove console.log
```suggestion
```

2023-04-13 23:49 UTC, geoffreyparrier commented on components/streamer-list.vue
> +<template>
Add a space between script and template
```suggestion

<template>
```

2023-04-23 02:36 UTC, geoffreyparrier requested changes

2023-04-23 02:36 UTC, geoffreyparrier commented on components/streamer-list.vue
> +  console.log(streamers.value);
```suggestion

```

2023-04-23 02:36 UTC, geoffreyparrier commented on server/api/getTwitchStreamers.post.ts
> +  // console.log(streamers);
```suggestion

```

2023-04-23 02:36 UTC, geoffreyparrier commented on stores/streamersStore.ts
> +    });
```suggestion
    directusStreamers.forEach((dStreamer) => {
      const streamerId = streamers.value.findIndex(streamer => streamer.display_name === dStreamer.id);
      streamers.value[streamerId].online = dStreamer.online;
    });
```

2023-04-24 21:08 UTC, geoffreyparrier requested changes

2023-04-24 21:08 UTC, geoffreyparrier commented on server/api/getTwitchStreamers.post.ts
> +    options
```suggestion
    options,
```
C'est normal qu'on ait les , en fin de tout, ça améliore la lecture, l'écriture et sur github aussi

2023-05-24 17:01 UTC, closed without merging